#!/usr/bin/env node
/**
 * sync.mjs — project the neutral playbooks/ tree into each harness's skills directory.
 *
 *   node .claude/tools/sync.mjs            write the projections
 *   node .claude/tools/sync.mjs --check    exit 2 if any projection is stale (use in CI)
 *   node .claude/tools/sync.mjs --list     show the targets and their state
 *
 * playbooks/ is the source of truth. Everything under a target directory is generated
 * and must never be hand-edited — the .generated marker in each target records the
 * source hash so --check can tell you when someone did.
 *
 * Copies, not symlinks: symlinks need developer mode or an elevated shell on Windows,
 * and a procedure whose install step fails on half the team is not a procedure.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, statSync } from 'node:fs';
import { resolve, join, relative } from 'node:path';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { ROOT, loadConfig } from './tracker.mjs';

const MARKER = '.generated';

function walk(dir, base = dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === MARKER) continue;
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(p, base));
    else out.push(relative(base, p).split('\\').join('/'));
  }
  return out;
}

function hashTree(dir) {
  const h = createHash('sha256');
  for (const f of walk(dir).sort()) {
    h.update(f);
    h.update(readFileSync(join(dir, f)));
  }
  return h.digest('hex').slice(0, 16);
}

function copyTree(src, dst) {
  if (existsSync(dst)) rmSync(dst, { recursive: true, force: true });
  for (const f of walk(src)) {
    const to = join(dst, f);
    mkdirSync(resolve(to, '..'), { recursive: true });
    writeFileSync(to, readFileSync(join(src, f)));
  }
}

function main() {
  const cfg = loadConfig();
  const srcDir = resolve(ROOT, cfg.playbooks?.source ?? 'playbooks');
  const targets = cfg.playbooks?.targets ?? ['.claude/skills', '.agents/skills'];
  const mode = process.argv.includes('--check') ? 'check' : process.argv.includes('--list') ? 'list' : 'write';

  if (!existsSync(srcDir)) {
    process.stderr.write(`sync.mjs: no playbooks directory at ${srcDir}\n`);
    process.exit(1);
  }

  const books = readdirSync(srcDir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(srcDir, e.name, 'SKILL.md')))
    .map((e) => e.name)
    .sort();

  if (!books.length) {
    process.stderr.write(`sync.mjs: ${srcDir} contains no <name>/SKILL.md playbooks\n`);
    process.exit(1);
  }

  const report = { ok: true, mode, source: cfg.playbooks?.source ?? 'playbooks', playbooks: books, targets: {} };
  let stale = 0;

  for (const target of targets) {
    const targetDir = resolve(ROOT, target);
    const state = {};
    for (const name of books) {
      const from = join(srcDir, name);
      const to = join(targetDir, name);
      const want = hashTree(from);
      const markerPath = join(to, MARKER);
      const have = existsSync(markerPath) ? (JSON.parse(readFileSync(markerPath, 'utf8')).hash ?? null) : null;
      const drifted = !existsSync(to) || have !== want || (existsSync(to) && hashTree(to) !== want);

      if (mode === 'write' && drifted) {
        copyTree(from, to);
        writeFileSync(markerPath, JSON.stringify({
          $comment: 'GENERATED by .claude/tools/sync.mjs — do not edit anything in this directory. Edit the source and re-run sync.',
          source: `${report.source}/${name}`,
          hash: want,
          generated: new Date().toISOString().slice(0, 10),
        }, null, 2) + '\n');
      }
      if (drifted && mode !== 'write') stale++;
      state[name] = mode === 'write' ? (drifted ? 'written' : 'current') : (drifted ? 'STALE' : 'current');
    }
    report.targets[target] = state;
  }

  if (mode === 'check' && stale) {
    report.ok = false;
    report.error = `${stale} projection(s) are stale — run: node .claude/tools/sync.mjs`;
    process.stdout.write(JSON.stringify(report, null, 2) + '\n');
    process.stderr.write(`\n${report.error}\n`);
    process.exit(2);
  }
  process.stdout.write(JSON.stringify(report, null, 2) + '\n');
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) main();
